export const PERMISSIONS = [
  'MANAGE_USERS',
  'MANAGE_ROLES',
  'VIEW_PATIENTS',
  'EDIT_PATIENTS',
  'VIEW_APPOINTMENTS',
  'EDIT_APPOINTMENTS',
  'VIEW_DASHBOARD',
];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  ADMIN: [
    'MANAGE_USERS',
    'MANAGE_ROLES',
    'VIEW_PATIENTS',
    'EDIT_PATIENTS',
    'VIEW_APPOINTMENTS',
    'EDIT_APPOINTMENTS',
    'VIEW_DASHBOARD',
  ],
  DOCTOR: [
    'VIEW_PATIENTS',
    'EDIT_PATIENTS',
    'VIEW_APPOINTMENTS',
    'EDIT_APPOINTMENTS',
    'VIEW_DASHBOARD',
  ],
  RECEPTIONIST: [
    'VIEW_PATIENTS',
    'EDIT_PATIENTS',
    'VIEW_APPOINTMENTS',
    'EDIT_APPOINTMENTS',
    'VIEW_DASHBOARD',
  ],
};
